// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/shared/session_types.proto

package shared

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token          string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	UserAgent      string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress      string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	IsValid        bool                   `protobuf:"varint,6,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActivityAt int64                  `protobuf:"varint,8,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	Device         *Device                `protobuf:"bytes,9,opt,name=device,proto3" json:"device,omitempty"`
	Location       *Location              `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	mi := &file_proto_shared_session_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_session_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_proto_shared_session_types_proto_rawDescGZIP(), []int{0}
}

func (x *SessionData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SessionData) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionData) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SessionData) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *SessionData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionData) GetLastActivityAt() int64 {
	if x != nil {
		return x.LastActivityAt
	}
	return 0
}

func (x *SessionData) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *SessionData) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_proto_shared_session_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_session_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_shared_session_types_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_shared_session_types_proto protoreflect.FileDescriptor

const file_proto_shared_session_types_proto_rawDesc = "" +
	"\n" +
	" proto/shared/session_types.proto\x12\x06shared\x1a\x19proto/shared/common.proto\"\xd3\x02\n" +
	"\vSessionData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x19\n" +
	"\bis_valid\x18\x06 \x01(\bR\aisValid\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12(\n" +
	"\x10last_activity_at\x18\b \x01(\x03R\x0elastActivityAt\x12&\n" +
	"\x06device\x18\t \x01(\v2\x0e.common.DeviceR\x06device\x12,\n" +
	"\blocation\x18\n" +
	" \x01(\v2\x10.common.LocationR\blocation\"E\n" +
	"\x0fSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x16Z\x14evolvia/proto/sharedb\x06proto3"

var (
	file_proto_shared_session_types_proto_rawDescOnce sync.Once
	file_proto_shared_session_types_proto_rawDescData []byte
)

func file_proto_shared_session_types_proto_rawDescGZIP() []byte {
	file_proto_shared_session_types_proto_rawDescOnce.Do(func() {
		file_proto_shared_session_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shared_session_types_proto_rawDesc), len(file_proto_shared_session_types_proto_rawDesc)))
	})
	return file_proto_shared_session_types_proto_rawDescData
}

var (
	file_proto_shared_session_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_proto_shared_session_types_proto_goTypes  = []any{
		(*SessionData)(nil),     // 0: shared.SessionData
		(*SessionResponse)(nil), // 1: shared.SessionResponse
		(*Device)(nil),          // 2: common.Device
		(*Location)(nil),        // 3: common.Location
	}
)
var file_proto_shared_session_types_proto_depIdxs = []int32{
	2, // 0: shared.SessionData.device:type_name -> common.Device
	3, // 1: shared.SessionData.location:type_name -> common.Location
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shared_session_types_proto_init() }
func file_proto_shared_session_types_proto_init() {
	if File_proto_shared_session_types_proto != nil {
		return
	}
	file_proto_shared_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shared_session_types_proto_rawDesc), len(file_proto_shared_session_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_shared_session_types_proto_goTypes,
		DependencyIndexes: file_proto_shared_session_types_proto_depIdxs,
		MessageInfos:      file_proto_shared_session_types_proto_msgTypes,
	}.Build()
	File_proto_shared_session_types_proto = out.File
	file_proto_shared_session_types_proto_goTypes = nil
	file_proto_shared_session_types_proto_depIdxs = nil
}
