// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/auth/auth.proto

package auth

import (
	shared "proto-gen/shared"
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_auth_auth_proto protoreflect.FileDescriptor

const file_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x15proto/auth/auth.proto\x12\x04auth\x1a proto/shared/session_types.proto2\x9c\x01\n" +
	"\vAuthService\x12G\n" +
	"\x17SendSessionToMiddleware\x12\x13.shared.SessionData\x1a\x17.shared.SessionResponse\x12D\n" +
	"\fAuthenGoogle\x12\x17.shared.GoogleLoginData\x1a\x1b.shared.GoogleLoginResponseB\x10Z\x0eproto-gen/authb\x06proto3"

var file_proto_auth_auth_proto_goTypes = []any{
	(*shared.SessionData)(nil),         // 0: shared.SessionData
	(*shared.GoogleLoginData)(nil),     // 1: shared.GoogleLoginData
	(*shared.SessionResponse)(nil),     // 2: shared.SessionResponse
	(*shared.GoogleLoginResponse)(nil), // 3: shared.GoogleLoginResponse
}

var file_proto_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.SendSessionToMiddleware:input_type -> shared.SessionData
	1, // 1: auth.AuthService.AuthenGoogle:input_type -> shared.GoogleLoginData
	2, // 2: auth.AuthService.SendSessionToMiddleware:output_type -> shared.SessionResponse
	3, // 3: auth.AuthService.AuthenGoogle:output_type -> shared.GoogleLoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_proto_init() }
func file_proto_auth_auth_proto_init() {
	if File_proto_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_proto_depIdxs,
	}.Build()
	File_proto_auth_auth_proto = out.File
	file_proto_auth_auth_proto_goTypes = nil
	file_proto_auth_auth_proto_depIdxs = nil
}
