// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/middleware/middleware.proto

package middleware

import (
	"middleware/pkg/proto/shared"
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_middleware_middleware_proto protoreflect.FileDescriptor

const file_proto_middleware_middleware_proto_rawDesc = "" +
	"\n" +
	"!proto/middleware/middleware.proto\x12\n" +
	"middleware\x1a proto/shared/session_types.proto2S\n" +
	"\x11MiddlewareService\x12>\n" +
	"\x0eProcessSession\x12\x13.shared.SessionData\x1a\x17.shared.SessionResponseB\x1aZ\x18evolvia/proto/middlewareb\x06proto3"

var file_proto_middleware_middleware_proto_goTypes = []any{
	(*shared.SessionData)(nil),     // 0: shared.SessionData
	(*shared.SessionResponse)(nil), // 1: shared.SessionResponse
}

var file_proto_middleware_middleware_proto_depIdxs = []int32{
	0, // 0: middleware.MiddlewareService.ProcessSession:input_type -> shared.SessionData
	1, // 1: middleware.MiddlewareService.ProcessSession:output_type -> shared.SessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_middleware_middleware_proto_init() }
func file_proto_middleware_middleware_proto_init() {
	if File_proto_middleware_middleware_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_middleware_middleware_proto_rawDesc), len(file_proto_middleware_middleware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_middleware_middleware_proto_goTypes,
		DependencyIndexes: file_proto_middleware_middleware_proto_depIdxs,
	}.Build()
	File_proto_middleware_middleware_proto = out.File
	file_proto_middleware_middleware_proto_goTypes = nil
	file_proto_middleware_middleware_proto_depIdxs = nil
}
