// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/google/google_service.proto

package google

import (
	shared "proto-gen/shared"
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_google_google_service_proto protoreflect.FileDescriptor

const file_proto_google_google_service_proto_rawDesc = "" +
	"\n" +
	"!proto/google/google_service.proto\x12\x0egoogle_service\x1a proto/shared/session_types.proto2Z\n" +
	"\rGoogleService\x12I\n" +
	"\x11ProcessGoogleAuth\x12\x17.shared.GoogleLoginData\x1a\x1b.shared.GoogleLoginResponseB\x1aZ\x18proto-gen/google_serviceb\x06proto3"

var file_proto_google_google_service_proto_goTypes = []any{
	(*shared.GoogleLoginData)(nil),     // 0: shared.GoogleLoginData
	(*shared.GoogleLoginResponse)(nil), // 1: shared.GoogleLoginResponse
}

var file_proto_google_google_service_proto_depIdxs = []int32{
	0, // 0: google_service.GoogleService.ProcessGoogleAuth:input_type -> shared.GoogleLoginData
	1, // 1: google_service.GoogleService.ProcessGoogleAuth:output_type -> shared.GoogleLoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_google_google_service_proto_init() }
func file_proto_google_google_service_proto_init() {
	if File_proto_google_google_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_google_google_service_proto_rawDesc), len(file_proto_google_google_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_google_google_service_proto_goTypes,
		DependencyIndexes: file_proto_google_google_service_proto_depIdxs,
	}.Build()
	File_proto_google_google_service_proto = out.File
	file_proto_google_google_service_proto_goTypes = nil
	file_proto_google_google_service_proto_depIdxs = nil
}
